@startuml

class Observable {
    +subscribe(Observer): Subscription
}

class Observer {
    +subscription: Subscription
    +onNext(item)
    +onError(error)
    +onCompleted()
}

class Subscription {
    +unsubscribe()
}

Observable --> Observer
Observer --> Subscription
Subscription --> Observable

@enduml